### ISSUE TITLE
Error on upgrading to Crystal 0.36.0

### ISSUE THREAD

**Issue by matthewmcgarvey** [icy-arctic-fox/spectator#20]
I was updating the Shrine shard and found that it had specs like `it is_expected.to be_nil`. https://github.com/jetrockets/shrine.cr/blob/f897acbdc7efe4269442854bd6db1bda85fe3fdc/spec/shrine/uploaded_file_spec.cr#L73

I'm not sure if this worked on Crystal 0.35 but on 0.36 it produces an error like

```bash
In lib/spectator/src/spectator/source.cr:11:20

 11 | def initialize(@file, @line)
                     ^----
Error: instance variable '@file' of Spectator::Source must be String, not Nil
```

It ultimately is coming from this line returning nil instead of the filename string https://github.com/icy-arctic-fox/spectator/blob/eee5d3888d9c8c5ac2d921d2312623495f22e571/src/spectator/dsl/examples.cr#L21

After changing the specs to have the expectation wrapped in curly braces the error went away. I believe this is an invalid spec call so maybe special handling should be added to catch it and raise a friendly error?

**Comment by icy-arctic-fox** [comment]
I'm surprised this worked before. In this syntax:

```crystal
it is_expected.to be_nil
```

there's no block, and the macro code is asking for the filename and line number of the non-existent block. You're correct in that surrounding the test with braces would fix it, since that introduces a block.

```crystal
it { is_expected.to be_nil }
```

There will be a fix for this shortly.

I had planned to deprecate the brace-less syntax in the next version of Spectator. However, I've seen quite a few people using this syntax and am having second thoughts. This syntax isn't supported in RSpec (for probably obvious reasons), but it can look quite elegant. What are your thoughts?

**Comment by matthewmcgarvey** [comment]
This is my first time using spectator so I'm probably not the best person to ask for an opinion about this shard.

My opinion would be to remove that style of spec. My first thought after tracking down the problem specs was that they probably never worked correctly but I think you're saying that they used to.

**Comment by icy-arctic-fox** [comment]
It seems that either something changed in the Crystal compiler (Nop used to have non-nil source values) or this broke in the last Spectator update, which aligns somewhat with the release of Crystal 0.36.0. [This change](https://github.com/icy-arctic-fox/spectator/commit/2ecd4ded6d7f9ac6c3cf10c47652c82aab0e81e9#diff-1e3cff03451b9a50f18bc5c69d73a4dac7e0ea77eb61e11681a93b953741201d) switched from using `__FILE__` and `__LINE__`, since they were unreliable in macros, to using the block's AST data. Do you know when this broke exactly? If I had to guess, it was the last version of Spectator that caused the issue. Either way, not too important, it's fixed now :smile:

**Comment by matthewmcgarvey** [comment]
Fixed by https://github.com/icy-arctic-fox/spectator/commit/8d48e441b2fbdb0922f12620411cef804b292432
