### ISSUE TITLE
GitLab or GitHub

### ISSUE THREAD

**Issue by matthewmcgarvey** [icy-arctic-fox/spectator#22]
It seems like you keep this repo and your [GitLab repo](https://gitlab.com/arctic-fox/spectator) in sync commit-wise, but there are different open issues in both. I'm about to open a GitHub PR but I have no idea if I should actually make it on GitLab instead.

Which repo is/should be the main one and which is a mirror? Could you add something to the README to help us understand?

**Comment by icy-arctic-fox** [comment]
Issues and pull requests are accepted on both. GitLab is the primary repository - it's where I push to and the CI pipeline runs. GitLab synchronizes to GitHub on push. For GitHub pull requests, I perform a command-line merge on the GitLab side, which GitHub detects. As far as the end-user is concerned, they're the same codebase.

The mirror to GitHub was mainly made for developers. More people use the public GitHub than GitLab - I don't want to force people to create yet another account just because I prefer GitLab. Additionally, some shard aggregators don't scan GitLab.

The README briefly mentions that issues and PRs are accepted in both locations. Perhaps that could be expanded upon to add information about sync and such. I don't want to over-complicate the text too much so that developers are confused as to what to do. Thoughts?

**Comment by matthewmcgarvey** [comment]
Anything is better than nothing in this case 😄 

Just mentioning that both places are fine to raise issues / make pull requests would be great

**Comment by icy-arctic-fox** [comment]
Hopefully addressed with recent changes.
