### ISSUE TITLE
How to test when exit() is called?

### ISSUE THREAD

**Issue by postmodern** [icy-arctic-fox/spectator#29]
Attempting to port some RSpec specs to Crystal which tests when the top-level `exit` method is called.

```ruby
expect(subject).to receive(:exit).with(0)
```

Unfortunately, the Spectator method hook doesn't intercept the `exit` method call, and the process exits prematurely.

**Comment by icy-arctic-fox** [comment]
It seems that Spectator isn't stubbing the exit method. There needs to be a stub defined prior to calling `receive(:exit)`. For instance:

```crystal
class SomeClass
  def goodbye
    exit
  end
end

mock SomeClass do
  stub exit
end

it "captures exit" do
  expect(subject).to receive(:exit).with(0)
  subject.goodbye
end
```

This code doesn't work though, since `exit` isn't defined in `SomeClass` - it's a top-level method. Another issue is that a type is required for the `mock` block, but there isn't one for a top-level method. (maybe `Object`?)

Do you have any code that shows this in action in RSpec?

**Comment by postmodern** [comment]
Code: https://github.com/postmodern/command_kit/blob/a06a131ddde42fa7f7730debbdc66136282bae1f/lib/command_kit/main.rb#L46-L56
RSpec specs: https://github.com/postmodern/command_kit/blob/a06a131ddde42fa7f7730debbdc66136282bae1f/spec/main_spec.rb#L28-L100

**Comment by icy-arctic-fox** [comment]
This should be possible in v0.9.39 - Can you try it out and confirm?

The following spec works:

```crystal
require "../spec_helper"

Spectator.describe "GitHub Issue #29" do
  class SomeClass
    def goodbye
      exit 0
    end
  end

  mock SomeClass do
    stub exit(code)
  end

  describe SomeClass do
    it "captures exit" do
      expect(subject).to receive(:exit).with(0)
      subject.goodbye
    end
  end
end
```

**Comment by postmodern** [comment]
Ah, stubbing/capturing exit now works on instances, but not at the class-level. I'm guessing `mock`/`stub` is assuming `exit` is an instance method?

```crystal
require "./spec_helper"

Spectator.describe "test exit" do
  class Foo
    def self.test
      exit 0
    end
  end

  mock Foo do
    stub exit(code)
  end

  subject { Foo }

  it "must capture exit" do
    expect(subject).to receive(:exit).with(0)

    subject.test
  end
end
```

```
$ crystal spec spec/test_spec.cr 
test exit
```

**Comment by icy-arctic-fox** [comment]
I think I see why this is happening. I'll try to get a fix in.

**Comment by icy-arctic-fox** [comment]
Should be resolved in v0.9.40, can you verify?

For class methods that call `exit`, it will need to stub `self.exit(code)`.

**Comment by postmodern** [comment]
Confirmed `self.exit(code)` works.

**Comment by icy-arctic-fox** [comment]
Heads up, this is changing in v0.11. Instead of relying on stubs, `exit` will raise a `Spectator::SystemExit` error. This [mimics what RSpec does](https://stackoverflow.com/questions/1480537/how-can-i-validate-exits-and-aborts-in-rspec). See the [related spec for this issue](https://gitlab.com/arctic-fox/spectator/-/merge_requests/35/diffs#0d3aea657e845478b615c3d779e28edaf3b98e5f) for an example.
